=== codegooglecom/torpor-php/trunk/src/TorporConfig.xsd
<?xml version="1.0"?>
<!-- $Rev$ -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.tricornersoftware.com/Products/Torpor/Config/0.1" xmlns="http://www.tricornersoftware.com/Products/Torpor/Config/0.1" elementFormDefault="unqualified">
	<xs:element name="TorporConfig" type="TorporConfig"/>
	<xs:complexType name="TorporConfig">
		<xs:sequence>
			<xs:element minOccurs="0" name="Options">
				<xs:complexType>
					<xs:sequence>
						<xs:element default="true" minOccurs="0" name="CacheReferencedGrids"/>
						<xs:element default="false" minOccurs="0" name="CacheReferencedGridSets"/>
						<xs:element default="Column" minOccurs="0" name="ColumnClass">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:pattern value="[a-zA-Z_][a-zA-Z0-9_]*"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:element>
						<xs:element default="false" minOccurs="0" name="Debug" type="xs:boolean"/>
						<xs:element default="Grid" minOccurs="0" name="GridClass">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:pattern value="[a-zA-Z_][a-zA-Z0-9_]*"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:element>
						<xs:element default="true" minOccurs="0" name="LinkUnpublishedReferenceColumns" type="xs:boolean"/>
						<xs:element default="true" minOccurs="0" name="OverwriteOnLoad" type="xs:boolean"/>
						<xs:element default="-1" minOccurs="0" name="PageSize">
							<xs:simpleType>
								<xs:restriction base="xs:integer">
									<xs:minInclusive value="-1"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:element>
						<xs:element default="false" minOccurs="0" name="PermitDDL" type="xs:boolean"/>
						<xs:element default="false" minOccurs="0" name="PerpetuateAutoLinks" type="xs:boolean"/>
						<xs:element default="false" minOccurs="0" name="PublishAllColumns" type="xs:boolean"/>
						<xs:element default="true" minOccurs="0" name="PublishDependencies" type="xs:boolean"/>
						<xs:element default="true" minOccurs="0" name="ReloadAfterPublish" type="xs:boolean"/>
						<xs:element default="true" minOccurs="0" name="TypedGridClasses" type="xs:boolean"/>
						<xs:element default="" minOccurs="0" name="TypedGridClassesPrefix">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:pattern value="([a-zA-Z_][a-zA-Z0-9_]*)?"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:element>
						<xs:element minOccurs="0" name="DataTypeMap">
							<xs:complexType>
								<xs:sequence>
									<xs:element form="unqualified" maxOccurs="unbounded" name="DataMap">
										<xs:complexType>
											<xs:attribute name="class" use="required">
												<xs:simpleType>
													<xs:restriction base="xs:string">
														<xs:pattern value="[a-zA-Z_][a-zA-Z0-9_]*"/>
													</xs:restriction>
												</xs:simpleType>
											</xs:attribute>
											<xs:attribute name="type" use="required">
												<xs:simpleType>
													<xs:restriction base="xs:string">
														<xs:enumeration value="binary"/>
														<xs:enumeration value="bool"/>
														<xs:enumeration value="char"/>
														<xs:enumeration value="class"/>
														<xs:enumeration value="date"/>
														<xs:enumeration value="datetime"/>
														<xs:enumeration value="float"/>
														<xs:enumeration value="integer"/>
														<xs:enumeration value="text"/>
														<xs:enumeration value="time"/>
														<xs:enumeration value="unsigned"/>
														<xs:enumeration value="varchar"/>
													</xs:restriction>
												</xs:simpleType>
											</xs:attribute>
										</xs:complexType>
									</xs:element>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element minOccurs="0" name="Repository">
				<xs:complexType>
					<xs:sequence minOccurs="1">
						<xs:element minOccurs="0" name="Cache">
							<xs:complexType>
								<xs:sequence minOccurs="0">
									<xs:element maxOccurs="unbounded" minOccurs="0" name="Parameter">
										<xs:complexType mixed="true">
											<xs:attribute name="name" type="xs:string" use="required"/>
											<xs:attribute name="value" type="xs:string"/>
										</xs:complexType>
									</xs:element>
								</xs:sequence>
								<xs:attribute name="class" use="required">
									<xs:simpleType>
										<xs:restriction base="xs:string">
											<xs:pattern value="[a-zA-Z_][a-zA-Z0-9_]*"/>
										</xs:restriction>
									</xs:simpleType>
								</xs:attribute>
							</xs:complexType>
						</xs:element>
						<xs:choice>
							<xs:element name="DataStore">
								<xs:complexType>
									<xs:sequence minOccurs="0">
										<xs:element maxOccurs="unbounded" minOccurs="0" name="Parameter">
											<xs:complexType mixed="true">
												<xs:attribute name="name" type="xs:string" use="required"/>
												<xs:attribute name="value" type="xs:string"/>
												<xs:attribute default="false" name="encrypted" type="xs:boolean"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="class">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:pattern value="[a-zA-Z_][a-zA-Z0-9_]*"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="type" type="xs:string" use="required"/>
								</xs:complexType>
							</xs:element>
							<xs:sequence>
								<xs:element name="ReadDataStore">
									<xs:complexType>
										<xs:sequence minOccurs="0">
											<xs:element maxOccurs="unbounded" minOccurs="0" name="Parameter">
												<xs:complexType mixed="true">
													<xs:attribute name="name" type="xs:string" use="required"/>
													<xs:attribute name="value" type="xs:string"/>
													<xs:attribute default="false" name="encrypted" type="xs:boolean"/>
												</xs:complexType>
											</xs:element>
										</xs:sequence>
										<xs:attribute name="class">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:pattern value="[a-zA-Z_][a-zA-Z0-9_]*"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:attribute>
										<xs:attribute name="type" type="xs:string" use="required"/>
									</xs:complexType>
								</xs:element>
								<xs:element name="WriteDataStore">
									<xs:complexType>
										<xs:sequence minOccurs="0">
											<xs:element maxOccurs="unbounded" minOccurs="0" name="Parameter">
												<xs:complexType mixed="true">
													<xs:attribute name="name" type="xs:string" use="required"/>
													<xs:attribute name="value" type="xs:string"/>
													<xs:attribute default="false" name="encrypted" type="xs:boolean"/>
												</xs:complexType>
											</xs:element>
										</xs:sequence>
										<xs:attribute name="type" type="xs:string" use="required"/>
										<xs:attribute name="class">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:pattern value="[a-zA-Z_][a-zA-Z0-9_]*"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:attribute>
									</xs:complexType>
								</xs:element>
							</xs:sequence>
						</xs:choice>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="Grids">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Grid" maxOccurs="unbounded" minOccurs="1">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="Columns" minOccurs="0">
										<xs:complexType>
											<xs:sequence>
												<xs:element maxOccurs="unbounded" minOccurs="1" name="Column">
													<xs:complexType>
														<xs:attribute name="class" use="optional">
															<xs:simpleType>
																<xs:restriction base="xs:string">
																	<xs:pattern value="[a-zA-Z_][a-zA-Z0-9_]*"/>
																</xs:restriction>
															</xs:simpleType>
														</xs:attribute>
														<xs:attribute name="dataName" type="xs:string" use="required"/>
														<xs:attribute name="default" type="xs:string"/>
														<xs:attribute name="encoding" type="xs:string"/>
														<xs:attribute default="false" name="generatedOnPublish" type="xs:boolean"/>
														<xs:attribute default="-1" name="length">
															<xs:simpleType>
																<xs:restriction base="xs:integer">
																	<xs:minInclusive value="-1"/>
																</xs:restriction>
															</xs:simpleType>
														</xs:attribute>
														<xs:attribute name="name">
															<xs:simpleType>
																<xs:restriction base="xs:string">
																	<xs:pattern value="[a-zA-Z_][a-zA-Z0-9_]*"/>
																</xs:restriction>
															</xs:simpleType>
														</xs:attribute>
														<xs:attribute default="true" name="nullable" type="xs:boolean"/>
														<xs:attribute default="0" name="precision" type="xs:integer"/>
														<xs:attribute default="false" name="readOnly" type="xs:boolean"/>
														<xs:attribute name="type" use="required">
															<xs:simpleType>
																<xs:restriction base="xs:string">
																	<xs:enumeration value="binary"/>
																	<xs:enumeration value="bool"/>
																	<xs:enumeration value="char"/>
																	<xs:enumeration value="class"/>
																	<xs:enumeration value="date"/>
																	<xs:enumeration value="datetime"/>
																	<xs:enumeration value="float"/>
																	<xs:enumeration value="integer"/>
																	<xs:enumeration value="text"/>
																	<xs:enumeration value="time"/>
																	<xs:enumeration value="unsigned"/>
																	<xs:enumeration value="varchar"/>
																</xs:restriction>
															</xs:simpleType>
														</xs:attribute>
													</xs:complexType>
												</xs:element>
											</xs:sequence>
										</xs:complexType>
									</xs:element>
									<xs:element name="Commands" minOccurs="0">
										<xs:complexType>
											<xs:sequence>
												<xs:element name="Command" maxOccurs="unbounded">
													<xs:complexType>
														<xs:sequence>
															<xs:element name="CommandText">
																<xs:complexType mixed="true">
																	<xs:attribute name="type" type="xs:string"/>
																	<xs:attribute default="?" name="placeholder" type="xs:string"/>
																</xs:complexType>
															</xs:element>
															<xs:element maxOccurs="unbounded" minOccurs="0" name="CommandParameter">
																<xs:complexType>
																	<xs:attribute name="column" type="xs:string" use="required"/>
																	<xs:attribute default="?" name="placeholder" type="xs:string"/>
																</xs:complexType>
															</xs:element>
														</xs:sequence>
														<xs:attribute name="type" use="required">
															<xs:simpleType>
																<xs:restriction base="xs:string">
																	<xs:enumeration value="delete"/>
																	<xs:enumeration value="load"/>
																	<xs:enumeration value="publish"/>
																</xs:restriction>
															</xs:simpleType>
														</xs:attribute>
														<xs:attribute name="context">
															<xs:simpleType>
																<xs:restriction base="xs:string">
																	<xs:enumeration value="new"/>
																	<xs:enumeration value="existing"/>
																	<xs:enumeration value="all"/>
																</xs:restriction>
															</xs:simpleType>
														</xs:attribute>
													</xs:complexType>
												</xs:element>
											</xs:sequence>
										</xs:complexType>
									</xs:element>
									<xs:element minOccurs="0" name="DataTypeMap">
										<xs:complexType>
											<xs:sequence>
												<xs:element form="unqualified" maxOccurs="unbounded" name="DataMap">
													<xs:complexType>
														<xs:attribute name="type" use="required">
															<xs:simpleType>
																<xs:restriction base="xs:string">
																	<xs:enumeration value="binary"/>
																	<xs:enumeration value="bool"/>
																	<xs:enumeration value="char"/>
																	<xs:enumeration value="class"/>
																	<xs:enumeration value="date"/>
																	<xs:enumeration value="datetime"/>
																	<xs:enumeration value="float"/>
																	<xs:enumeration value="integer"/>
																	<xs:enumeration value="text"/>
																	<xs:enumeration value="time"/>
																	<xs:enumeration value="unsigned"/>
																	<xs:enumeration value="varchar"/>
																</xs:restriction>
															</xs:simpleType>
														</xs:attribute>
														<xs:attribute name="class" use="required">
															<xs:simpleType>
																<xs:restriction base="xs:string">
																	<xs:pattern value="[a-zA-Z_][a-zA-Z0-9_]*"/>
																</xs:restriction>
															</xs:simpleType>
														</xs:attribute>
													</xs:complexType>
												</xs:element>
											</xs:sequence>
										</xs:complexType>
									</xs:element>
									<xs:element name="Keys" minOccurs="0">
										<xs:complexType>
											<xs:sequence>
												<xs:element minOccurs="0" name="Foreign">
													<xs:complexType>
														<xs:sequence>
															<xs:element maxOccurs="unbounded" name="Key">
																<xs:complexType>
																	<xs:attribute name="column" type="xs:string" use="required"/>
																	<xs:attribute name="referenceColumn" type="xs:string"/>
																	<xs:attribute name="referenceGrid" type="xs:string" use="required"/>
																	<xs:attribute name="referenceGridAlias" type="xs:string"/>
																</xs:complexType>
															</xs:element>
														</xs:sequence>
													</xs:complexType>
												</xs:element>
												<xs:element minOccurs="0" name="Primary">
													<xs:complexType>
														<xs:sequence>
															<xs:element maxOccurs="unbounded" name="Key">
																<xs:complexType>
																	<xs:attribute name="column" type="xs:string" use="required"/>
																</xs:complexType>
															</xs:element>
														</xs:sequence>
													</xs:complexType>
												</xs:element>
												<xs:element maxOccurs="unbounded" minOccurs="0" name="Unique">
													<xs:complexType>
														<xs:sequence>
															<xs:element maxOccurs="unbounded" name="Key">
																<xs:complexType>
																	<xs:attribute name="column" type="xs:string" use="required"/>
																</xs:complexType>
															</xs:element>
														</xs:sequence>
													</xs:complexType>
												</xs:element>
											</xs:sequence>
										</xs:complexType>
									</xs:element>
								</xs:sequence>
								<xs:attribute name="class">
									<xs:simpleType>
										<xs:restriction base="xs:string">
											<xs:pattern value="[a-zA-Z_][a-zA-Z0-9_]*"/>
										</xs:restriction>
									</xs:simpleType>
								</xs:attribute>
								<xs:attribute name="dataName" type="xs:string" use="required"/>
								<xs:attribute name="name" type="xs:string"/>
								<xs:attribute default="false" name="readOnly" type="xs:boolean"/>
								<xs:attribute default="data" name="type">
									<xs:simpleType>
										<xs:restriction base="xs:string">
											<xs:enumeration value="data"/>
											<xs:enumeration value="map"/>
										</xs:restriction>
									</xs:simpleType>
								</xs:attribute>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="version" form="unqualified" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:float">
					<xs:minInclusive value="0"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
</xs:schema>

=== codegooglecom/torpor-php/trunk/src/TorporConfig.sample.xml
<?xml version="1.0"?>
<!-- Pre-amble here is just used to determine the conventions of this XML document  -->
<!-- and the namespace to which it belongs.  "trpr" is the important namespace,     -->
<!-- resolving to the URI which uniquely identifies this as a TorporConfig (version -->
<!-- 0.1 in this case) document, and to be validated by that schema accordingly.    -->
<!-- The schema document location is also specified for reference via               -->
<!-- schemaLocation, and the xsi namespace is also established so that reference    -->
<!-- can be made.  If you're familiar with XML and schemas this should be pretty    -->
<!-- straightforward, if not you can feel safe to copy and paste.                   -->
<!-- NOTE: The version indicator here is for the version of the configuration type  -->
<!-- and does *not* correspond to Torpor release version necessarily.               -->
<trpr:TorporConfig
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.tricornersoftware.com/Products/Torpor/Config/0.1 TorporConfig.xsd"
	xmlns:trpr="http://www.tricornersoftware.com/Products/Torpor/Config/0.1"
	version="0.1">

	<!-- Complete list of supported options and their default values.  Any of these -->
	<!-- settings may be omitted, and the default value (shown below) will be used  -->
	<!-- instead.  The entire Options section may be omitted, and all defaults will -->
	<!-- be used. -->
	<Options>

		<!-- If set to true, when one Grid is used as the source for fetching another -->
		<!-- related Grid, the source Grid will cache a reference in that context to  -->
		<!-- the resulting object.  This means that not only will repeated calls      -->
		<!-- produce the same Grid record, they will produce it as represented by the -->
		<!-- the same object reference.  This is a performance enhancement which      -->
		<!-- allows for useful repeat call patterns such as:                          -->
		<!--  if( $someGrid->getRelatedRecord()->Load() ){                            -->
		<!--      doSoemthingTo( $someGrid->getRelatedRecord() );                     -->
		<!--  } -->
		<CacheReferencedGrids>true</CacheReferencedGrids>

		<!-- Similar in purpose to <CacheReferencedGrids/>, this sets whether or not -->
		<!-- to do the same with GridSet objects.  This is off by default, as the    -->
		<!-- relationship between a Grid and resulting GridSet is less tightly       -->
		<!-- tightly coupled than from one Grid to another (examples of the loose    -->
		<!-- coupling include multiple source Grids and other Criteria settings).    -->
		<CacheReferencedGridSets>false</CacheReferencedGridSets>

		<!-- This is the PHP class name which will be used as the base prototype    -->
		<!-- for every Grid's Column (unless overwridden further down in the line). -->
		<ColumnClass>Column</ColumnClass>

		<!-- May cause more E_USER_NOTICE values to be produced.  Debug classes are -->
		<!-- a wiser choice, allowing more targetted hooks. -->
		<Debug>false</Debug>

		<!-- PHP class name for all Grid prototypes. -->
		<GridClass>Grid</GridClass>
		
		<!--   This rather long-named option controls whether or not, when using a -->
		<!-- Grid as a factory for a related Grid, or associating two Grids in a   -->
		<!-- specific context, whether or not to automaticall "link" the           -->
		<!-- corresponding reference Columns between the two in a situation where: -->
		<!--    1. A reference Column does not currently have data                 -->
		<!--    2. That Column is set to "GeneratedOnPublish"                      -->
		<!--   This allows Grid types which have late-binding keys established by  -->
		<!-- the repository to still be associated to one another without having   -->
		<!-- to summarily publish everything just to get a key.  Once established, -->
		<!-- any request to the source Column for data will be redirected to the   -->
		<!-- now linked target Column to retrieve it's data (if it has any), which -->
		<!-- which will then be stored locally (with the source Column) and        -->
		<!-- finally returned to the calling interface.                            -->
		<!--   Such a pattern allows objects with late binding primary keys, for   -->
		<!-- example, to be associated with one another prior to publishing, which -->
		<!-- in turn improves performance and prevents partial records from being  -->
		<!-- written to the repository for the sole purpose of retrieving a key,   -->
		<!-- or making some other key-determining round trip (e.g., fetch from a   -->
		<!-- sequence) for resources which may not even be used, in the instance   -->
		<!-- that the publish never actually takes place.                          -->
		<!--   This has bearing on <PublishDependencies/>: these are the           -->
		<!-- dependencies it's referring to.  If a linked Column is encountered    -->
		<!-- with no data of its own, and the target of that link is generated on  -->
		<!-- publish, that target will be published first and the resulting key    -->
		<!-- propagated to the originating object. See <PerpetuateAutoLinks/> too. -->
		<LinkUnpublishedReferenceColumns>true</LinkUnpublishedReferenceColumns>

		<!-- Determines whether, when loading an object from persistence, whether -->
		<!-- to overwite any data which was set prior to that Grid's ability to   -->
		<!-- load (determined when one or more discrete sets of unique Columns    -->
		<!-- has been set).  Defaults to true, as shown here, which means any     -->
		<!-- data already set (which does not correspond to the loaded data) will -->
		<!-- be wiped out.  This will also generate an E_USER_NOTICE to indicate  -->
		<!-- somebody's data is going missing, in case this results in aberrant   -->
		<!-- or unexpected behavior. -->
		<OverwriteOnLoad>true</OverwriteOnLoad>

		<!-- The number of records to fetch from the repository for GridSet type -->
		<!-- objects where the local GridSet page size has not been explicitly   -->
		<!-- set.  A negative number corresponds to "all available records," and -->
		<!-- is not recommended (especially for web apps) unless you really need -->
		<!-- all records.  However, this is the default in order to avoid nasty  -->
		<!-- surprises in the form of failing to operate on all records matching -->
		<!-- requested criteria. -->
		<PageSize>-1</PageSize>

		<!-- Whether or not any data description language (modifications to  -->
		<!-- repository structure) will be permitted.  Disabled by default,  -->
		<!-- and probably only useful if one plans on working with temporary -->
		<!-- tables and the like.  Whether or not something is DDL is up to  -->
		<!-- the repository handler to figure out, and for that handler to   -->
		<!-- query this setting - it is not pushed, nor does Torpor intro-   -->
		<!-- spect incoming queries. -->
		<PermitDDL>false</PermitDDL>

		<!-- Used together with <LinkUnpublishedReferenceColumns/>, this setting -->
		<!-- indicates whether or not to maintain that linked relationship after -->
		<!-- data has been retrieved from the target Column.  When set to false, -->
		<!-- as soon as some data has been retrieved from the target Column the  -->
		<!-- link will be severed and the 2 will go their separate ways.  This   -->
		<!-- is the default, since reference keys between records are not        -->
		<!-- expected to change with sufficient frequency to warrant contining   -->
		<!-- the link.  If set to true, however, the 2 objects will continue to  -->
		<!-- operate in tandem; useful if keys are expected to be changing for   -->
		<!-- some reason. -->
		<!-- NOTE: The source Column data is not pushed to by the target Column; -->
		<!-- the link relationship is one strictly of pull to source from target -->
		<!-- when the source Column's data is requested.  Thus it's possible to  -->
		<!-- change the target Column's data many times before the source Column -->
		<!-- ever wises up.  Just FYI. -->
		<PerpetuateAutoLinks>false</PerpetuateAutoLinks>

		<!-- Determines whether or not to publish all Columns, or just those which -->
		<!-- have changed.  Applies to loaded Grids only (since all newly created  -->
		<!-- records will be published in their entirey anyway), and is not        -->
		<!-- recommended as "false" for use with distributed caching, since the    -->
		<!-- Cache interface is an "all or nothing" rather than a delta set.  This -->
		<!-- feature helps performance with small web apps and can assist in       -->
		<!-- reducing incidental data overwrites at the final repository level,    -->
		<!-- but as mentioned above would be largely superceded by the use of      -->
		<!-- distributed caching and should be set to true in those environments.  -->
		<!--   This is most useful in those data adapters which do not support     -->
		<!-- pre-compiled queries (with data placeholders) for performance,  since -->
		<!-- it does require that custom queries be assembled each time which      -->
		<!-- negate any pre-compilation performance gain. -->
		<PublishAllColumns>false</PublishAllColumns>

		<!-- If a required Column does not have data, and is Linked to a Column which -->
		<!-- also does not have data but is set to GeneratedOnPublish, this setting   -->
		<!-- determines whether to publish the linked target Column in order to       -->
		<!-- retrieve its data for use in the Column we're intending to publish which -->
		<!-- requires it.  This is a recursive-safe operation in that it will detect  -->
		<!-- circular references, but only in that it will detect them - it will end  -->
		<!-- up throwing an exception rather than segfaultiing is all. -->
		<PublishDependencies>true</PublishDependencies>

		<!-- Once a Grid has been published, this setting determines whether to mark -->
		<!-- the Grid as not yet having loaded, such that subsequent requests for    -->
		<!-- data will cause the just-in-time load to fire.  Though this slightly    -->
